### ISSUE TITLE
Error receiving a null field from Location

### ISSUE THREAD

**Issue by JosephFC1995** [KeenenCharles/AndroidUnplash#4]
How can I solve this problem

`java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.kc.unsplash.models.Location.getCountry()' on a null object reference
                                                                                          at asociazation.company.fis.ver.examplo.PhotoDetails$2.onComplete(PhotoDetails.java:115)
                                                                                          at com.kc.unsplash.Unsplash$3.onResponse(Unsplash.java:193)
                                                                                          at retrofit2.ExecutorCallAdapterFactory$ExecutorCallbackCall$1$1.run(ExecutorCallAdapterFactory.java:68)`

**Comment by KeenenCharles** [comment]
Looks like the location you're trying to access is null. Make sure you check for that not all photos will have a location.

**Comment by JjoZex** [comment]
This happens to me in the new photos, sometimes the users upload photos without indicating the place, I think it is an error of the same page. Thanks for answering
